sonar.projectKey=Address-book-system
sonar.working.directory=C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system
sonar.pullrequest.cache.basepath=C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system

89B55FC6-F162-414F-9C19-E1C732F96675.sonar.projectKey=Address-book-system:89B55FC6-F162-414F-9C19-E1C732F96675
89B55FC6-F162-414F-9C19-E1C732F96675.sonar.projectName=address-book-system
89B55FC6-F162-414F-9C19-E1C732F96675.sonar.projectBaseDir=C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system
89B55FC6-F162-414F-9C19-E1C732F96675.sonar.sourceEncoding=utf-8
89B55FC6-F162-414F-9C19-E1C732F96675.sonar.tests=
89B55FC6-F162-414F-9C19-E1C732F96675.sonar.sources=\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\AddressBookExceptions.cs",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\AddressBookMain.cs",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\AddressBookModel.cs",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\AddressBookUtility.cs",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\DisplayAttribute.cs",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\IAddressBook.cs",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\RequiredAttribute.cs",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\AddressBook.csv",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\AddressBook.json",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\AddressBook.txt",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\obj\\address-book-system.csproj.nuget.dgspec.json",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\obj\\project.assets.json",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\bin\\Debug\\net10.0\\address-book-system.deps.json",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\bin\\Debug\\net10.0\\address-book-system.runtimeconfig.json",\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\obj\\Debug\\net10.0\\address-book-system.sourcelink.json"

89B55FC6-F162-414F-9C19-E1C732F96675.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\.sonarqube\\out\\0"
89B55FC6-F162-414F-9C19-E1C732F96675.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\.sonarqube\\out\\0\\Issues.json"
89B55FC6-F162-414F-9C19-E1C732F96675.sonar.cs.scanner.telemetry=\
"C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\.sonarqube\\out\\0\\Telemetry.json"

89B55FC6-F162-414F-9C19-E1C732F96675.sonar.working.directory=C:\\Users\\VARSH\\OneDrive\\Desktop\\BridgeLabz-Training\\ioprogramming-csharp-practice\\scenario-based\\address-book-system\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://127.0.0.1:9000
sonar.visualstudio.enable=false

sonar.modules=89B55FC6-F162-414F-9C19-E1C732F96675

